version: '3.8'

services:
  vacation-tracker:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./server/data.json:/app/server/data.json
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/members"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s